### ISSUE TITLE
dos packages

### ISSUE THREAD

**Issue by immetoo** [fr3nd/msxhub-packages#18]
Can we add packages like;
- DOS1 (msxdos.sys + command.com)
- DOS2 (msxdos2.sys + command2.com)
- DOSNTOR (nextor.sys + command2.com)

So that for example the binary files in the dsk folder; *.COM and *.SYS can be deleted and fetched from msxhub before needed in build/emulator step ?

**Comment by fr3nd** [comment]
That's actually a good idea. I already created the packages for [MSXDOS2T](https://msxhub.com/MSXDOS2T), [KIDS](https://msxhub.com/KIDS) and [MACRO80](https://msxhub.com/MACRO80), but not the MSXDOS ones.

I'll think how it can be implemented. The contents of the UTILS and HELP directories also need to be available.

**Comment by fr3nd** [comment]
please check #19

**Comment by immetoo** [comment]
That look nice, copyed files to a:\ rebooted now in version 2.20

**Comment by fr3nd** [comment]
I've added both [NEXTOR](https://msxhub.com/NEXTOR) and [MSXDOS2](https://msxhub.com/MSXDOS2).

Do you know where an official copy of the MSX-DOS1 disk can be downloaded?

**Comment by immetoo** [comment]
You mean this disk; https://www.generation-msx.nl/software/ascii-corporation/msx-dos-tools/910/ ?
I could only find;
http://www.msxarchive.nl/pub/msx/utils/misc/msxdos1.lzh
Maybe we could start with it and bump package revision if someone found a full dos1 ascii disk image ?

**Comment by immetoo** [comment]
Have added the dos1 package to close this issue.

I'm so happy with msxhub it works very nice in build pipelines to have no msx binary deps.
Have done it with some makefile magic; (as there is no native linux/win/mac msxhub fetcher ;)
https://code.distributedrebirth.love/arch-msx/msxbuild/src/branch/master/lib/make/mb_msxhub.mk

Now i can fetch msx resources as a make rule like;
$(GFX_BIN)/popcom.com: $(GFX_BIN)
	$(call mb_msxhub_file,$(GFX_BIN)/popcom.com,https://msxhub.com/api/POPCOM/1.00-1/get/POPCOM/popcom.com)

Have also taken the MARCO80 package and made a "Hello World" compile and link and test headless in 1 second;
`
willemc@black:~/devv/workspace-msx/msxbuild$ time make test-ahello-m80-assert      
mkdir -p bin/test/ahello-m80
/usr/bin/unix2dos -n test/ahello-m80/ahello.mac bin/test/ahello-m80/ahello.mac
unix2dos: converting file test/ahello-m80/ahello.mac to file bin/test/ahello-m80/ahello.mac in DOS format...
=== Generating autoexec.bat for command
echo -n "" > bin/test/ahello-m80/autoexec.bat
echo "rem Generated by msxbuild Makefile\r" >> bin/test/ahello-m80/autoexec.bat
echo "omsxctl fail_after 60 seconds fail_after_init 124\r" >> bin/test/ahello-m80/autoexec.bat
echo "mode 80\r" >> bin/test/ahello-m80/autoexec.bat
echo "echo Enabled mode 80.\r" >> bin/test/ahello-m80/autoexec.bat
echo "omsxctl fail_after 300 seconds fail_after_cmd 1\r" >> bin/test/ahello-m80/autoexec.bat
echo "echo Running command 'm80 =ahello/Z'\r" >> bin/test/ahello-m80/autoexec.bat
echo "m80 =ahello/Z\r" >> bin/test/ahello-m80/autoexec.bat
echo "omsxctl exit 0\r" >> bin/test/ahello-m80/autoexec.bat
cp ~/.cache/msxhub/repro-v0/MACRO80/2.0-1/get/MACRO80/CREF80.COM bin/test/ahello-m80/cref80.com
cp ~/.cache/msxhub/repro-v0/MACRO80/2.0-1/get/MACRO80/L80.COM bin/test/ahello-m80/l80.com
cp ~/.cache/msxhub/repro-v0/MACRO80/2.0-1/get/MACRO80/LIB80.COM bin/test/ahello-m80/lib80.com
cp ~/.cache/msxhub/repro-v0/MACRO80/2.0-1/get/MACRO80/M80.COM bin/test/ahello-m80/m80.com
cp ~/.cache/msxhub/repro-v0/MSXDOS2/2.20-1/get/MSXDOS2/MSXDOS2.SYS bin/test/ahello-m80/msxdos2.sys
cp ~/.cache/msxhub/repro-v0/MSXDOS2/2.20-1/get/MSXDOS2/COMMAND2.COM bin/test/ahello-m80/command2.com
cp ~/.cache/msxhub/repro-v0/OMSXCTL/1.0-1/get/OMSXCTL/omsxctl.com bin/test/ahello-m80/omsxctl.com
=== Running openMSX
FAIL_AFTER_BOOT=25 FAIL_AFTER_PATH=bin BOOT_HDD_PATH="bin/test/ahello-m80" BOOT_HDD_IMAGE="bin/test/ahello-m80/../dsk.img" JOYPORTA= JOYPORTB= /opt/openMSX/bin/openmsx -setting /home/willemc/devv/workspace-msx/msxbuild/lib/openmsx/boot_settings.xml -machine Philips_NMS_8250 -ext slotexpander -ext ide -ext ram4mb  -script /home/willemc/devv/workspace-msx/msxbuild/lib/openmsx/boot_env.tcl -script /home/willemc/devv/workspace-msx/msxbuild/lib/openmsx/boot_hdd.tcl -script /home/willemc/devv/workspace-msx/msxbuild/lib/openmsx/fail_after.tcl -script ~/.cache/msxhub/repro-v0/OMSXCTL/1.0-1/get/OMSXCTL/omsxctl.tcl -control stdio < /home/willemc/devv/workspace-msx/msxbuild/lib/openmsx/boot_stdio.xml | sed -n -e 's/.*>\(.*\)<.*/\1/p' | tail -n+3
=== Generating autoexec.bat for command
echo -n "" > bin/test/ahello-m80/autoexec.bat
echo "rem Generated by msxbuild Makefile\r" >> bin/test/ahello-m80/autoexec.bat
echo "omsxctl fail_after 60 seconds fail_after_init 124\r" >> bin/test/ahello-m80/autoexec.bat
echo "mode 80\r" >> bin/test/ahello-m80/autoexec.bat
echo "echo Enabled mode 80.\r" >> bin/test/ahello-m80/autoexec.bat
echo "omsxctl fail_after 300 seconds fail_after_cmd 1\r" >> bin/test/ahello-m80/autoexec.bat
echo "echo Running command 'l80 ahello,ahello/N/X/Y/E'\r" >> bin/test/ahello-m80/autoexec.bat
echo "l80 ahello,ahello/N/X/Y/E\r" >> bin/test/ahello-m80/autoexec.bat
echo "omsxctl exit 0\r" >> bin/test/ahello-m80/autoexec.bat
=== Running openMSX
FAIL_AFTER_BOOT=25 FAIL_AFTER_PATH=bin BOOT_HDD_PATH="bin/test/ahello-m80" BOOT_HDD_IMAGE="bin/test/ahello-m80/../dsk.img" JOYPORTA= JOYPORTB= /opt/openMSX/bin/openmsx -setting /home/willemc/devv/workspace-msx/msxbuild/lib/openmsx/boot_settings.xml -machine Philips_NMS_8250 -ext slotexpander -ext ide -ext ram4mb  -script /home/willemc/devv/workspace-msx/msxbuild/lib/openmsx/boot_env.tcl -script /home/willemc/devv/workspace-msx/msxbuild/lib/openmsx/boot_hdd.tcl -script /home/willemc/devv/workspace-msx/msxbuild/lib/openmsx/fail_after.tcl -script ~/.cache/msxhub/repro-v0/OMSXCTL/1.0-1/get/OMSXCTL/omsxctl.tcl -control stdio < /home/willemc/devv/workspace-msx/msxbuild/lib/openmsx/boot_stdio.xml | sed -n -e 's/.*>\(.*\)<.*/\1/p' | tail -n+3
=== Extracting hex2com
cd bin/test/ahello-m80/ && ~/devv/workspace-msx/Hex2bin-2.5/hex2bin -e com ahello.hex
hex2bin v2.5, Copyright (C) 2017 Jacques Pelletier & contributors

Allocate_Memory_and_Rewind:
Lowest address:   00000100
Highest address:  0000011C
Starting address: 00000100
Max Length:       29

Binary file start = 00000100
Records start     = 00000100
Highest address   = 0000011C
Pad Byte          = FF
test bin/test/ahello-m80/test.out && rm -f bin/test/ahello-m80/test.out
=== Generating autoexec.bat for command test
echo -n "" > bin/test/ahello-m80/autoexec.bat
echo "rem Generated by msxbuild Makefile\r" >> bin/test/ahello-m80/autoexec.bat
echo "omsxctl fail_after 60 seconds fail_after_init 124\r" >> bin/test/ahello-m80/autoexec.bat
echo "mode 80\r" >> bin/test/ahello-m80/autoexec.bat
echo "echo Enabled mode 80.\r" >> bin/test/ahello-m80/autoexec.bat
echo "omsxctl fail_after 120 seconds fail_after_test 1\r" >> bin/test/ahello-m80/autoexec.bat
echo "echo Running test 'ahello > test.out'\r" >> bin/test/ahello-m80/autoexec.bat
echo "ahello > test.out\r" >> bin/test/ahello-m80/autoexec.bat
echo "omsxctl exit 0\r" >> bin/test/ahello-m80/autoexec.bat
=== Running openMSX
FAIL_AFTER_BOOT=25 FAIL_AFTER_PATH=bin BOOT_HDD_PATH="bin/test/ahello-m80" BOOT_HDD_IMAGE="bin/test/ahello-m80/../dsk.img" JOYPORTA= JOYPORTB= /opt/openMSX/bin/openmsx -setting /home/willemc/devv/workspace-msx/msxbuild/lib/openmsx/boot_settings.xml -machine Philips_NMS_8250 -ext slotexpander -ext ide -ext ram4mb  -script /home/willemc/devv/workspace-msx/msxbuild/lib/openmsx/boot_env.tcl -script /home/willemc/devv/workspace-msx/msxbuild/lib/openmsx/boot_hdd.tcl -script /home/willemc/devv/workspace-msx/msxbuild/lib/openmsx/fail_after.tcl -script ~/.cache/msxhub/repro-v0/OMSXCTL/1.0-1/get/OMSXCTL/omsxctl.tcl -control stdio < /home/willemc/devv/workspace-msx/msxbuild/lib/openmsx/boot_stdio.xml | sed -n -e 's/.*>\(.*\)<.*/\1/p' | tail -n+3
grep "M80: Hello world..." bin/test/ahello-m80/test.out
M80: Hello world...

real    0m1.021s
user    0m0.858s
sys     0m0.593s
`

**Comment by fr3nd** [comment]
Wow, that's very nice indeed. An automated compilation process running in MSX... I'm so glad to see that MSXHub is used for this kind of projects.
🔝
