### ISSUE TITLE
Error 5 on make

### ISSUE THREAD

**Issue by Fubukimaru** [fr3nd/msxhub-packages#23]
Hello!

I'm trying to add LHEXT and TuNzIp programs to the hub as the recent advancements in Ducasp's telnet client allow us to download compressed files from BBSs like Hispamsx. 
https://github.com/Fubukimaru/msxhub-packages

I have a fork with the yamls that define the packages, however when testing them (and also already present packages) I get `Error 5`.

```
make tt
docker run -it --rm -u $(id -u) -v $(pwd):/usr/src fr3nd/msxhub-packages:5 pytest-3 -k packages/tt.yaml
======================= test session starts =======================
platform linux -- Python 3.6.7, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /usr/src, inifile:
collected 62 items                                                

======================= 62 tests deselected =======================
================== 62 deselected in 0.06 seconds ==================
make: *** [Makefile:12: tt] Error 5
```

Is this ok? How do I fix it?

**Comment by fr3nd** [comment]
Hi,

Bear in mind the packages are in capital letters and make is a case-sensitive tool. It looks like the command you want to run is `make TT`

**Comment by Fubukimaru** [comment]
That was it!

Thanks :)
