### ISSUE TITLE
MEMMAN Package: errors in it

### ISSUE THREAD

**Issue by ducasp** [fr3nd/msxhub-packages#35]
Hi fr3nd,

MEMMAN package has two issues:

1. TSR\SHIFT.TSR is listed twice, as TSR\SHIFT.TSR and as TSR\shift.tsr . As MSXDOS file names is not case sensitive, only one file is created and when uninstalling the package there is a warning about file not existing (as it deletes the first one that is the same as the second one, so when the time comes to delete the second one it doesn't exist)

2. The way pages are being listed is causing MSX HUB to not be able to delete MEMMAN\TSR folder, and thus, in the end not being able to delete MEMMAN folder. It starts listing two files in \TSR folder, then it starts creating several folders and files withing \TSR folder, and then it will start to save in \TSR folder more files again. The end result is that HUB will fail to remove TSR folder because the way HUB client works it will list the folder to remove only once, and will save it in the database when creating a different folder (and won't create a new entry in the database when saving the files again).

Probably it is possible to work around 2 in the client, but 1 is definitively a package failure.

**Comment by fr3nd** [comment]
Good catch! Thanks for reporting. This should be fixed once the new package is available :)
