### ISSUE TITLE
make <package> html page output

### ISSUE THREAD

**Issue by immetoo** [fr3nd/msxhub-packages#72]
It would be very helpfull to have an html page output of the package.
This for the description formatting, so the page should almost look like an msxhub.com page.

**Comment by fr3nd** [comment]
At the end the description of the package uses Markdown for the format. Any markdown previewer should show a very close approximation of how it will look like in the web.

For example:
* https://markdownlivepreview.com/

**Comment by immetoo** [comment]
Yes we know, what i meant is that make <package> or make <package>-html build target outputs the (full) html version.
Is it possible to copy the ~20lines of python+template from the msxhub codebase and add it as a make target ?

**Comment by fr3nd** [comment]
I honestly think this is out of the scope for the make script. It's supposed to be used to automate the creation of the packages, and I'm not sure how useful it would be to see HTML in the console without parsing...

Considering that there are already many tools that can do this task, I think I will close this issue.
