### ISSUE TITLE
Flag CP/M software

### ISSUE THREAD

**Issue by immetoo2** [fr3nd/msxhub-packages#83]
MSX BDOS is CP/M compatible so some of the tools are CP/M software.

Could a method be added howto flag this kind of software ?
- system: CP/M requirement: MSX-DOS
- system: MSX requirement: CP/M

**Comment by fr3nd** [comment]
Hi @immetoo 

I see. I understand the difference between MSX-DOS and CP/M, but at the end, if it's an MSX software designed to run in MSX-DOS, why should we specify this difference? I mean, if at the end it will work in MSX-DOS (because it is CP/M compatible), maybe adding CP/M as a requirement could be confusing to some people?

**Comment by immetoo** [comment]
Both methods are confusing, thought of adding property but that is ugly too.
But when working on the "Linguasphere Observatory" an tree path db for human languages, i got an idea to extend it to computer languages, but also all cpu asm formats and thus also those binary formats.
It will take some time to workout the correct classification id tree, but to give an example;
```
CF= Control Freak codezone
CF-A Cpu devices // mmu, dma, blitter, vdp, oplX, nic
CF-AA 1bit
CF-AAA Motorola
CF-AAA-a MC14500B
CF-AB 2bit
CF-AC 3bit
CF-AD 4bit
CF-AE 8bit
CF-AEA intel
CF-AEA-a i8080
CF-AEA-b i8088
CF-AEB Zilog
CF-AEB-a z80
```
And than with the (example) internal key "CF-AEB-a" a computer can get the binary schema for z80 program code, etc.
After which all the computer (z80,6502,etc) platforms (MSX) can be classified as a digital lingua tree paths.

Other example of software which needs a "tag";
Howto add packages which depend on the http://www.symbos.de/ runtime ?

**Comment by immetoo2** [comment]
Closing as this can't be added to msxhub version 1, the above (ascii) treekey is for version 4 which is for 18 bit BDOS which is a split from BDOS 2.2 (msx1) because the folder api is wrong in msx2 and above.
