### ISSUE TITLE
Add MSXDOS1T

### ISSUE THREAD

**Issue by immetoo2** [fr3nd/msxhub-packages#93]
The following tools are available from https://www.msx.org/wiki/Dragon_Disk_03#DOS_Tools
- CLS.COM
- ECHO.COM
- KEY.COM
- SYS.COM
- VERSION.COM
- VOLUME.COM

Steps needed to add msx dos1 tools;
- download disk03 from: https://download.file-hunter.com/Disk-Magazines/Dragon%20Disk/
- RUN"DOSTOOLS.LDR"
- copy extracted file to dos1tools.zip (without msx2.com)
- deploy dos1tools.zip for example to file-hunter
- create msxhub package

**Comment by immetoo** [comment]
Add COLOR.COM from https://github.com/gdx-msx/COLOR

**Comment by immetoo** [comment]
See msxdos2 commands and versions added on https://www.msx.org/wiki/MSX-DOS_Internal_Commands

**Comment by immetoo2** [comment]
Have tested msxdos1 tools from the dragon disk and they are not good, will create new verions of those, but the color command is what i need for msx1 support, so closing this.
